### ISSUE TITLE
Implementar autenticação com Spring Security.

### ISSUE THREAD

**Issue by jsantosrocha** [FIAP-SOAT7-2024-GP-Kotlin/SOAT7-MCKotlin-DDD#5]

**Comment by rafaeljpc** [comment]
precisa desse role agora?
e como vamos implementar? JWT puro ou OAuth2?

**Comment by jsantosrocha** [comment]
Inicialmente jwt depois coloco oauth2

Em ter., 23 de abr. de 2024 15:30, Rafael Correia ***@***.***>
escreveu:
